DROP TABLE IF EXISTS ClassRooms;
CREATE TABLE ClassRooms (
	ClassRoomID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	Address NVARCHAR(120) NOT NULL
);

DROP TABLE IF EXISTS Grades;
CREATE TABLE Grades (
	GradeID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	GradeDirector NVARCHAR(50) NOT NULL
);

DROP TABLE IF EXISTS Classes;
CREATE TABLE Classes (
	GradeID INTEGER NOT NULL,
	ClassID INTEGER NOT NULL,
	ClassRoomID INTEGER NOT NULL,
	ClassDirector NVARCHAR(50) NOT NULL,
    CONSTRAINT [PK_GradeIDClassID] PRIMARY KEY ([GradeID], [ClassID]),
    FOREIGN KEY ([GradeID]) REFERENCES [Grades] ([GradeID]) 
		ON DELETE NO ACTION ON UPDATE NO ACTION,
	FOREIGN KEY ([ClassRoomID]) REFERENCES [ClassRooms] ([ClassRoomID]) 
		ON DELETE NO ACTION ON UPDATE NO ACTION
);

DROP TABLE IF EXISTS Students;
CREATE TABLE Students (
	StudentID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	Name NVARCHAR(50) NOT NULL,
	Gender BIT NOT NULL DEFAULT(0),
	Birthday Date NOT NULL,
	Address NVARCHAR(120) NULL,
	GradeID INTEGER NOT NULL,
	ClassID INTEGER NOT NULL,
	FOREIGN KEY ([GradeID]) REFERENCES [Grades] ([GradeID]) 
		ON DELETE NO ACTION ON UPDATE NO ACTION,
	FOREIGN KEY ([ClassID]) REFERENCES [Classes] ([ClassID]) 
		ON DELETE NO ACTION ON UPDATE NO ACTION
);

DROP TABLE IF EXISTS Subjects;
CREATE TABLE Subjects (
	SubjectID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	SubjectName NVARCHAR(50) NOT NULL
);
CREATE UNIQUE INDEX [IDX_SubjectName] ON [Subjects]([SubjectName]);

DROP TABLE IF EXISTS Exams;
CREATE TABLE Exams (
	ExamID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	ExamTime DATETIME NOT NULL,
	SubjectID INTEGER NOT NULL,
	GradeID INTEGER NOT NULL,
	ClassID INTEGER NOT NULL,
	FOREIGN KEY ([SubjectID]) REFERENCES [Subjects] ([SubjectID]) 
		ON DELETE NO ACTION ON UPDATE NO ACTION,
	FOREIGN KEY ([GradeID]) REFERENCES [Grades] ([GradeID]) 
		ON DELETE NO ACTION ON UPDATE NO ACTION,
	FOREIGN KEY ([ClassID]) REFERENCES [Classes] ([ClassID]) 
		ON DELETE NO ACTION ON UPDATE NO ACTION
);
CREATE UNIQUE INDEX [IDX_GradeIDClassIDExamTime] ON [Exams]([GradeID], [ClassID], [ExamTime]);
CREATE INDEX [IDX_GradeIDClassIDSubjectID] ON [Exams]([GradeID], [ClassID], [SubjectID]);

DROP TABLE IF EXISTS Scores;
CREATE TABLE Scores (
	ScoreID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	ExamID INTEGER NOT NULL,
	StudentID INTEGER NOT NULL,
	Score DOUBLE NOT NULL,
	FOREIGN KEY ([ExamID]) REFERENCES [Exams] ([ExamID]) 
		ON DELETE NO ACTION ON UPDATE NO ACTION,
	FOREIGN KEY ([StudentID]) REFERENCES [Students] ([StudentID]) 
		ON DELETE NO ACTION ON UPDATE NO ACTION
);
CREATE UNIQUE INDEX [IDX_ExamIDStudentID] ON [Scores]([ExamID], [StudentID]);
